// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orfurjvqtdyuxeicdxml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yZnVyanZxdGR5dXhlaWNkeG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyODQzNTMsImV4cCI6MjA3MDg2MDM1M30.WJwy6b3WFX7cI_75ebUBz51LmYCOsnRjQfW0Fuc54Wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});